/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-01-31 07:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.MemberDAO;
import vo.BoardVO;
import dao.BoardDAO;

public final class boarddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 MemberDAO dao2 = new MemberDAO(); 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 보기</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t$(\"#update\").on(\"click\", function(){\r\n");
      out.write("\t\tif($(\"#authority\").val() == \"TRUE\") {\r\n");
      out.write("\t\t\tlocation.href = \"boardupdate.jsp\"\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\talert(\"작성자만 수정할 수 있습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); // update end\r\n");
      out.write("\t$(\"#delete\").on(\"click\", function(){\r\n");
      out.write("\t\tif($(\"#authority\").val() == \"TRUE\") {\r\n");
      out.write("\t\t\tlocation.href = \"boarddetailsdelete.jsp\"\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\talert(\"작성자만 삭제할 수 있습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); // delete end\r\n");
      out.write("\t}); // ready end\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("table{text-align: center; margin: auto; border: 1px solid purple;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


int seq = Integer.parseInt(request.getParameter("boardseq"));
session.setAttribute("boardseq", seq);
BoardDAO dao = new BoardDAO();
dao.viewCount(seq);
BoardVO vo = dao.getBoardDetail(seq);
session.setAttribute("boardvo", vo);

String boardwriter = vo.getBoardwriter();
String boardtitle = vo.getBoardtitle();
String boardcontents = vo.getBoardcontents();
String boardtime = vo.getBoardtime();
int boardviewcount = vo.getBoardviewcount();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"2px\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>게시물 번호</td><td>");
      out.print(seq);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>제목</td><td>");
      out.print(boardtitle);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td height = 300>내용</td><td width = 500>");
      out.print(boardcontents);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>작성자</td><td>");
      out.print(boardwriter);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>작성 시간</td><td>");
      out.print(boardtime);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>조회수</td><td>");
      out.print(boardviewcount);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<form action=\"boardupdate.jsp\">\r\n");
      out.write("\t\t<input type=button id='update' value=\"수정\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<form action=\"boarddetailsdelete.jsp\">\r\n");
      out.write("\t\t<input type=button id='delete' value=\"삭제\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<form action=\"boardlist.jsp\">\r\n");
      out.write("\t\t<input type=submit value=\"목록으로 돌아가기\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 상태 확인 태그-->\r\n");
      out.write('\r');
      out.write('\n');
String authority = dao2.authority(session, boardwriter); 
      out.write("   \r\n");
      out.write("<input type=\"hidden\" id=\"authority\" value=");
      out.print(authority);
      out.write(">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
