/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-07 12:53:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인 화면</title>\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-3.2.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$(\"#login\").click(function() {\n");
      out.write("\t\tvar id=$(\"#id\").val();\n");
      out.write("\t\tvar pw=$(\"#pw\").val();\n");
      out.write("\t\tvar param=\"id=\"+id+\"&pw=\"+pw;\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\ttype: \"get\",\n");
      out.write("\t\t\turl: \"login\",\n");
      out.write("\t\t\tdata: param,\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\t\t\t\t$(\"#div1\").html(data);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}); // login end\n");
      out.write("}); // ready end\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
 if (session.getAttribute("id") != null) { 
      out.write("\n");
      out.write("\t<script>location.href = \"loginstatus.jsp\"; </script>\n");
 } 
      out.write("\n");
      out.write("<div id=\"div1\">\n");
      out.write("\n");
      out.write("\t<!-- 로그인 창 -->\n");
      out.write("\t<table border=\"1\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><input type=text id=\"id\" name=\"id\" placeholder=\"아이디\"></td>\n");
      out.write("\t\t\t<td rowspan=2><input type=\"button\" id=\"login\" value=\"로그인\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><input type=text id=\"pw\" name=\"pw\" placeholder=\"비밀번호\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table> \n");
      out.write("<a href = \"signin.jsp\">회원가입 하러 가기</a>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
