/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-09 01:23:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.RestaurantDAO;
import vo.RestaurantVO;
import java.util.ArrayList;
import dao.BoardDAO;

public final class restaurantlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


String[] province = {"강남구", "강동구", "강북구", "강서구", "관악구", "광진구", "구로구", "금천구",
            "노원구", "도봉구", "동대문구", "동작구", "마포구", "서대문구", "서초구", "성동구",
            "성북구", "송파구", "양천구", "영등포구", "용산구", "은평구", "종로구", "중구", "중랑구"};
RestaurantDAO dao = new RestaurantDAO(); 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>음식점 리스트</title>\n");
      out.write("\n");
      out.write("<script src=\"jquery-3.2.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t$(\"#search\").on('click',function(){\n");
      out.write("\t\t\tif($(\"#province option:selected\").val().length<1) {\n");
      out.write("\t\t\t\talert(\"지역을 선택하세요.\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif($(\"#closetime option:selected\").val().length<1) {\n");
      out.write("\t\t\t\talert(\"시간대를 선택하세요.\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t})\n");
      out.write("\t}); // ready end\n");
      out.write("\t\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\tdiv div.list {\n");
      out.write("\t\twidth: 250px;\n");
      out.write("\t\theight: 70%;\n");
      out.write("\t\tbackground-color: lightgray;\n");
      out.write("\t\tpadding: 10px\n");
      out.write("\t}\n");
      out.write("\tdiv div table.restaurant {\n");
      out.write("\t\twidth: 200px;\n");
      out.write("\t\theight: 100px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t}\n");
      out.write("\ttr,td {\n");
      out.write("\t\tborder: 1px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--게시판 제목-->\n");
      out.write("<div class=\"center\" id=\"div1\">\n");
      out.write("\t<!-- 제목 -->\n");
      out.write("\t<h1>음식점 목록입니다.</h1>\n");
      out.write("\t\n");
      out.write("\t<!-- selection form -->\n");
      out.write("\t<form action = \"restaurantlist.jsp\">\n");
      out.write("\t\t<!-- 구 선택 select-->\n");
      out.write("\t\t<select id=\"province\" name=\"province\"> \n");
      out.write("\t\t\t<option value='' selected>구를 선택하세요</option>\n");
      out.write("\t\t\t");
 for(int i = 0; i < province.length; i++) {
				out.println("<option value='"+province[i]+"'>" + province[i] + "</option>");
			}
      out.write("\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<!-- 시간 선택 => 마감시간으로 전달 select-->\n");
      out.write("\t\t<select id=\"closetime\" name=\"closetime\"> \n");
      out.write("\t\t\t<option value='' selected>원하는 시간대를 선택하세요</option>\n");
      out.write("\t\t\t<option id='23' value='23'>22:00-23:00시</option>\n");
      out.write("\t\t\t<option id='24' value='24'>23:00-24:00시</option>\n");
      out.write("\t\t\t<option id='01' value='01'>24:00-01:00시</option>\n");
      out.write("\t\t\t<option id='02' value='02'>01:00-02:00시</option>\n");
      out.write("\t\t\t<option id='03' value='03'>02:00-03:00시</option>\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<input id=\"search\" type=submit value=\"검색하기\">\n");
      out.write("\t</form>\n");
      out.write("\t\n");
      out.write("\t<!-- 식당 리스트 -->\n");
      out.write("\t<div class=\"list\">\n");
      out.write("\t\t");

			// 총 식당 개수 출력 - <span>
			int total=0;
			if (request.getParameter("province") !=null && request.getParameter("closetime") !=null) 
				{total = dao.getTotalRestaurants(request);	} 
			else {total = dao.getTotalRestaurants();	}
			out.println("<span>해당 지역 내 총 "+total+"개의 식당이 존재합니다.</span>");

			ArrayList<RestaurantVO> list = null;
			int pagenumb = 1; // 기본으로 보여줄 페이지
			int each = 10; // 페이지 당 보여주고 싶은 음식점 수
			
			// 페이지 번호 호출
			if(request.getParameter("page") != null){
				pagenumb = Integer.parseInt(request.getParameter("page"));
			}
			
			// 구, 마감시간 호출
			if (request.getParameter("province") !=null && request.getParameter("closetime") !=null) {
				list = dao.getSelectedList(request, pagenumb, each);
			} else {
				list = dao.getRestaurantList(pagenumb, each);
			}
			
			// 식당 리스트 출력
			for (int i = 0; i < list.size(); i++) {
			RestaurantVO vo = list.get(i);
			out.println (
					"<table class='restaurant' id='list"+i+"' border=1px><tr><td colspan='2'>" + vo.getName() + "</td></tr>" +
					"<tr><td colspan='2'>" + vo.getProvince() + " " + vo.getAddress() + "</td></tr>" +
					"<tr><td>"+ vo.getTag() + "</td><td>" + vo.getKeyword() + "</td></tr>" +
					"<tr><td colspan='2'> 마감시간 : " + vo.getClosetime() + ":00 시</td></tr></table>"
			);}
		
      out.write("\n");
      out.write("\t</div> \n");
      out.write("</div> \n");
      out.write("\n");
      out.write("<!--페이지 번호-->\n");
      out.write("<table class=\"center\" >\n");
      out.write("\t<tr>\n");
      out.write("\t<form action = \"mainpage.jsp\">\n");
      out.write("\t\t");

		int totalcont = dao.getTotalRestaurants();
		if (totalcont % each ==0){
			pagenumb = totalcont / each;
		} else {
			pagenumb = totalcont / each +1;
		}
		for (int i =1 ; i <= pagenumb; i ++){
		out.print("<td><input type=submit name='page' value='"+i+"'></td>");
		}
		
      out.write("\n");
      out.write("\t</form>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
