/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-20 05:08:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.BoardVO;
import java.util.ArrayList;
import dao.BoardDAO;

public final class boardlistsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 검색</title>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align=center>검색된 내용입니다.</h1>\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"list\" border=\"2px\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>번호</td>\r\n");
      out.write("\t\t\t<td width=\"250\">제목</td>\r\n");
      out.write("\t\t\t<td>작성자</td>\r\n");
      out.write("\t\t\t<td>작성시간</td>\r\n");
      out.write("\t\t\t<td>조회수</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			String tag = (String) request.getParameter("tag");
			String word = (String) request.getParameter("word");
			BoardDAO dao = new BoardDAO();
			ArrayList<BoardVO> list = dao.getBoardList(tag, word);

			for (int i = 0; i < list.size(); i++) {
				BoardVO vo = list.get(i);
				out.println("<tr><td>" + vo.getBoardseq() + "</td><td>" + "<a href = 'boarddetails.jsp?boardseq="
						+ vo.getBoardseq() + " '>" + vo.getBoardtitle() + "</a></td><td>" + vo.getBoardwriter()
						+ "</td><td>" + vo.getBoardtime() + "</td><td>" + vo.getBoardviewcount() + "</td></tr>");
			} // for문 end
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
