/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-21 10:57:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.BoardVO;
import dao.BoardDAO;

public final class boardupdateform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 수정</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".center {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.list {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@font-face {\r\n");
      out.write("\tfont-family: 'NEXEN TIRE_Regular';\r\n");
      out.write("\tsrc: url('assets/fonts/NEXEN TIRE_Regular.ttf') format('truetype');\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#up\").on(\r\n");
      out.write("\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar up = $(\"#up\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar newtitle = $(\"input[name='newtitle']\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar newcontents = $(\"textarea[name='newcontents']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tvar param = \"action=\" + up + \"&newtitle=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ newtitle + \"&newcontents=\" + newcontents\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"board\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".detail\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}); // update end\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".back\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\tvar referrer = document.referrer;\r\n");
      out.write("\t\t\t\t\tlocation.href = \"test.jsp\";\r\n");
      out.write("\t\t\t\t});// back end\r\n");
      out.write("\r\n");
      out.write("\t\t\t}); // ready end\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/form.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"overflow-x: hidden;\">\r\n");
      out.write("\t<p class=\"write\"\r\n");
      out.write("\t\tstyle=\"text-align: center; font-size: 1.5em; color: #585858; font-family: 'NEXEN TIRE_Regular';\">수정하기\r\n");
      out.write("\t</p>\r\n");
      out.write("\t");

		int seq = (Integer) session.getAttribute("boardseq");
		BoardDAO dao = new BoardDAO();
		BoardVO vo = (BoardVO) session.getAttribute("boardvo");
		int boardviewcount = vo.getBoardviewcount();

		String boardtitle = vo.getBoardtitle();
		String boardcontents = vo.getBoardcontents();
		String boardwriter = vo.getBoardwriter();
		String boardtime = vo.getBoardtime();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"detail\">\r\n");
      out.write("\t\t<p class=\"write\"\r\n");
      out.write("\t\t\tstyle=\"text-align: center; font-size: 1.5em; color: #585858; font-family: 'NEXEN TIRE_Regular';\">게시물\r\n");
      out.write("\t\t\t수정</p>\r\n");
      out.write("\t\t<table class=\"list\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rows=1 cols=100 name=\"boardtitle\" placeholder=\"제목을 입력하세요\"\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: 'NEXEN TIRE_Regular';\">게시물 번호</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(seq);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rows=1 cols=100 name=\"boardtitle\" placeholder=\"제목을 입력하세요\"\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: 'NEXEN TIRE_Regular';\">제목</td>\r\n");
      out.write("\t\t\t\t<td><input type=text name=\"newtitle\"\r\n");
      out.write("\t\t\t\t\tplaceholder=");
      out.print(boardtitle);
      out.write("></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=300>내용</td>\r\n");
      out.write("\t\t\t\t<td><textarea cols=70 rows=25 name=\"newcontents\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=");
      out.print(boardcontents);
      out.write("></textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>작성자</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(boardwriter);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>작성 시간</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(boardtime);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>조회수</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(boardviewcount);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=button name=\"write\" id=\"up\" value=\"수정\"\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: 'NEXEN TIRE_Regular';\">\r\n");
      out.write("\t\t\t\t\t<!-- <center> -->\r\n");
      out.write("\t\t\t\t\t<input type=button class='back' value=\"뒤로가기\"\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: 'NEXEN TIRE_Regular';\">\r\n");
      out.write("\t\t\t\t\t<!-- </center> -->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
