/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-21 10:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.BoardVO;

public final class boardwriteform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 입력</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" \t.center{text-align: center; margin: auto;}\r\n");
      out.write("\ttable.list{text-align: center; margin: 50px; } \r\n");
      out.write("\t@font-face {\r\n");
      out.write(" font-family: 'NEXEN TIRE_Regular';\r\n");
      out.write(" src: url('assets/fonts/NEXEN TIRE_Regular.ttf') format('truetype');\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$(\"input[name='write']\").on(\"click\", function(){\r\n");
      out.write("\t\tvar up=$(\"input[name='write']\").val();\r\n");
      out.write("\t\tvar boardtitle=$(\"input[name='boardtitle']\").val();\r\n");
      out.write("\t\tvar boardcontents=$(\"textarea[name='boardcontents']\").val();\r\n");
      out.write("\t\tvar param=\"action=\"+up+\"&boardtitle=\"+boardtitle+\"&boardcontents=\"+boardcontents\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"board\",\r\n");
      out.write("\t\t\tdata: param,\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$(\".detail\").html(data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}); // update end\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#back\").on(\"click\", function(){\r\n");
      out.write("\t\tvar referrer =  document.referrer;\r\n");
      out.write("\t\tlocation.href = \"test.jsp\";\r\n");
      out.write("\t});// back end\r\n");
      out.write("}); // ready end\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/form.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x:hidden\">\r\n");
      out.write("<div class=\"detail\" >\r\n");
      out.write("\t<p class = \"write\" style = \"text-align: center; font-size: 1.5em; color: #585858; font-family: 'NEXEN TIRE_Regular';\" >게시물 작성</p>\r\n");
      out.write("\t<table class=\"list\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><input rows=1 cols=100 name=\"boardtitle\" placeholder = \"제목을 입력하세요\" style = \" font-family: 'NEXEN TIRE_Regular';\"></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><textarea rows=10 cols=100 name=\"boardcontents\" placeholder = \"내용을 입력하세요 \"  style = \" font-family: 'NEXEN TIRE_Regular';\"></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><p style = \" font-family: 'NEXEN TIRE_Regular';s\">작성자 : ");
      out.print(session.getAttribute("id") );
      out.write("</p></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><input type=button name=\"write\" value=\"저장\" style = \"font-family: 'NEXEN TIRE_Regular';\"><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<center><input type=button class='back' value=\"뒤로가기\" style = \"font-family: 'NEXEN TIRE_Regular';\" ></center>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
