/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-22 05:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import dao.MemberDAO;
import vo.BoardVO;
import java.util.ArrayList;
import dao.BoardDAO;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	File f = new File(request.getRealPath(request.getRequestURI()));
	java.util.Date d = new java.util.Date( f.lastModified() );
	response.setHeader("Last-Modified", d.toString() );
	response.setHeader("ETag", d.toString() );

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>심야식당</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#login\").click(function() {\r\n");
      out.write("\t\t\tvar id=$(\"#id\").val();\r\n");
      out.write("\t\t\tvar pw=$(\"#pw\").val();\r\n");
      out.write("\t\t\tvar param=\"id=\"+id+\"&pw=\"+pw;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\turl: \"login\",\r\n");
      out.write("\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\t$(\".login_div\").html(data);\r\n");
      out.write("\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}); // login end\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* $(\"#login\").click(function() {\r\n");
      out.write("\t\t\tvar id=$(\"#id\").val();\r\n");
      out.write("\t\t\tvar pw=$(\"#pw\").val();\r\n");
      out.write("\t\t\tvar param=\"id=\"+id+\"&pw=\"+pw;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\turl: \"login\",\r\n");
      out.write("\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\t$(\"#div6\").html(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}); // login end */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".logout\").on(\"click\", function(){\r\n");
      out.write("\t         /* var id = session.getAttribute(\"id\"); */\r\n");
      out.write("\t         $.ajax({\r\n");
      out.write("\t            type: \"POST\",\r\n");
      out.write("\t            url: \"logout\",\r\n");
      out.write("\t            /* data: {\"id\" : id}, */\r\n");
      out.write("\t            success: function() {\r\n");
      out.write("\t               window.location.reload();\r\n");
      out.write("\t               alert(\"로그아웃 되었습니다.\");\r\n");
      out.write("\t            },\r\n");
      out.write("\t            error : function(){\r\n");
      out.write("\t                  alert(\"오류발생\")\r\n");
      out.write("\t                 }\r\n");
      out.write("\t            \r\n");
      out.write("\t         });\r\n");
      out.write("\t         return false;\r\n");
      out.write("\t         \r\n");
      out.write("\t      }); // logout end\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t}); // ready end\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<noscript>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/noscript.css\" />\r\n");
      out.write("</noscript>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/login.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/login.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/tab.css?after\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#intro\">심야 식당</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#map\">지도</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#one\">메뉴</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#two\">추천 식당</a></li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t");
 if(session.getAttribute("id")==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#work\"><b>로그인</b></a>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#work\"><b>로그아웃</b></a>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Intro -->\r\n");
      out.write("\t<section id=\"intro\" class=\"main style1 dark fullscreen\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\tWELCOME <br>심야식당\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong>심야식당</strong>에 오신 것을 환영합니다.<br />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t<a href=\"#map\" class=\"button style2 down\">More</a>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- map -->\r\n");
      out.write("\t<section id=\"map\" class=\"main style2 dark fullscreen\">\r\n");
      out.write("\t\t<div class=\"content box style2\"\r\n");
      out.write("\t\t\tstyle= width: 90%; height: 700px;\">\r\n");
      out.write("\t\t\t\t<table border=3px>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><h1 style=\"font-size:40px; line-height:3em\">서울의 심야식당</h1></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \t<td>\r\n");
      out.write("\t\t\t\t \t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"totalmap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe src='http://70.12.111.110:8081/nightrestaurant/leafletchart2/index2.html' width=400% height=400px seamless></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<h4> 해당 지역 내 총 <strong style=\"font-size:20px; color:#E80C50\">23,774</strong> 개의 식당이 존재합니다. </h3>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#one\" class=\"button style2 down anchored\">Next</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- One -->\r\n");
      out.write("\t<section id=\"one\" class=\"main style2 right dark fullscreen\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"content box style2\"\r\n");
      out.write("\t\t\tstyle=\"overflow-x: hidden; overflow-y: auto; width: 90%; height: 750px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"tab2-1\" id=\"tores\">심야 식당 찾기</label> <input id=\"tab2-1\"\r\n");
      out.write("\t\t\t\t\t\tname=\"tabs-two\" type=\"radio\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t\t<div id=\"tabA\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "restaurantlist.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"tab2-2\" id=\"toboard\">게시판 보기</label> <input id=\"tab2-2\"\r\n");
      out.write("\t\t\t\t\t\tname=\"tabs-two\" type=\"radio\">\r\n");
      out.write("\t\t\t\t\t<div id=\"tabB\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "boardlist.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#two\" class=\"button style2 down anchored\">Next</a>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Two -->\r\n");
      out.write("\t<section id=\"two\" class=\"main style2 left dark fullscreen\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Gallery  -->\r\n");
      out.write("\t\t<div class=\"gallery\">\r\n");
      out.write("\t\t\t<article class=\"from-left\">\r\n");
      out.write("\t\t\t\t<a class=\"image fit\"><img src=\"images/aps2.jpg\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"250\" title=\"The Anonymous Red\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>알프스 식당</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#흑석맛집 #중앙대맛집 #혼밥혼술 #게살튀김오짐<br>\r\n");
      out.write("\t\t\t\t\t\t\t#인스타갬성 #야끼소바 #세계음식\r\n");
      out.write("\t\t\t\t\t\t</font> <br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?id=1127738824\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t\t<article class=\"from-right\">\r\n");
      out.write("\t\t\t\t<a class=\"image fit\"><img src=\"images/baek.png\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"250\" title=\"Airchitecture II\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>백수씨 심야식당</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#경희대맛집 #회기맛집 #우육전 #해물안주<br>\r\n");
      out.write("\t\t\t\t\t\t\t#홍새우회 #서울의밤 #복고\r\n");
      out.write("\t\t\t\t\t\t</font><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?entry=plt&id=1224219974&query=%EB%B0%B1%EC%88%98%EC%94%A8%EC%8B%AC%EC%95%BC%EC%8B%9D%EB%8B%B9\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<article class=\"from-left\">\r\n");
      out.write("\t\t\t\t<a class=\"image fit\"><img src=\"images/bro.png\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"250\" title=\"Air Lounge\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>브로콜리 식당</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#망원동맛집 #망리단길 #분위기굿 #맛도굿<br>\r\n");
      out.write("\t\t\t\t\t\t\t#스키야끼 #일본가정식 #데이트코스\r\n");
      out.write("\t\t\t\t\t\t</font><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?entry=plt&id=38009356&query=%EB%B8%8C%EB%A1%9C%EC%BD%9C%EB%A6%AC%EC%8B%9D%EB%8B%B9\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<article class=\"from-right\">\r\n");
      out.write("\t\t\t\t<a class=\"image fit\"><img src=\"images/dong.png\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"250\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>동묘가라지</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#동묘24시맛집 #동묘펍 #피맥 #JMT맥주<br>\r\n");
      out.write("\t\t\t\t\t\t\t#동묘파스타 #존맛탱안주 #코젤다크시나몬\r\n");
      out.write("\t\t\t\t\t\t</font><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?id=1540634517\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<article class=\"from-left\">\r\n");
      out.write("\t\t\t\t<a class=\"image fit\"><img src=\"images/jblee.png\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"250\" title=\"The sparkling shell\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>주바리 프로젝트</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#이태원 #심야식당 #육사시미맛집 #엄마밥<br>\r\n");
      out.write("\t\t\t\t\t\t\t#다이어트내일부터 #스위스감자전 #셰프들의아지트\r\n");
      out.write("\t\t\t\t\t\t</font><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?entry=plt&id=35326713&query=%EC%8B%AC%EC%95%BC%EC%8B%9D%EB%8B%B9%20%EC%8B%9C%EC%A6%8C2%20%EC%A3%BC%EB%B0%94%EB%A6%AC%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<article class=\"from-right\">\r\n");
      out.write("\t\t\t\t<a href=\"\" target=\"_blank\" class=\"image fit\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/kitchen.png\" width=\"300\" height=\"250\" title=\"Bent IX\"\r\n");
      out.write("\t\t\t\t\talt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<b>밤키친</b><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <font size=\"2\">#방배동맛집 #오미자주 #1인키친 <br> #스테이크\r\n");
      out.write("\t\t\t\t\t\t\t#단호박크림리조또 #1인셰프\r\n");
      out.write("\t\t\t\t\t\t</font><br>\r\n");
      out.write("\t\t\t\t\t\t<br> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://store.naver.com/restaurants/detail?id=37524875\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"images/right-arrow.png\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"30px\" height=\"30px\"></a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#work\" class=\"button style2 down anchored\">Next</a>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Work -->\r\n");
      out.write("\t<section id=\"work\" class=\"main style3 primary\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 if (session.getAttribute("id")==null & session.getAttribute("pw")==null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"div3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 로그인창-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login_div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"left\" border=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input type=text id=\"id\" name=\"id\" placeholder=\"아이디\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td rowspan=2><input type=\"button\" id=\"login\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"로그인\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input type=text id=\"pw\" name=\"pw\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"비밀번호\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"left\" href=\"signin.jsp\">회원가입 하러 가기</a>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--로그인창 end-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"div3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><h3> ");
      out.print( session.getAttribute("id") );
      out.write(" 회원님 환영합니다.<br></h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=button class='logout' value='로그아웃'>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Contact -->\r\n");
      out.write("\t<section id=\"contact\" class=\"main style3 secondary\"\r\n");
      out.write("\t\tstyle=\"width: 100%; height: 300px;\"]>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<h2>See you again</h2>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tLa comida es la forma más primitiva de confort.<br>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 0.8em;\">\r\n");
      out.write("\t\t\t\t\t<b>\"좋은 음식은 좋은 대화로 끝이 난다.\" </b><br> by 조프리 네이어\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- <div class=\"box\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fields\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" placeholder=\"Name\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"Email\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"message\" placeholder=\"Message\" rows=\"6\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"actions special\">\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" /></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer id=\"footer\" style=\"height: 30px;\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Icons -->\r\n");
      out.write("      <ul class=\"icons\">\r\n");
      out.write("         <li><a href=\"#\" class=\"icon fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("         <li><a href=\"https://www.twitter.com\" target=\"_blank\" class=\"icon fa-twitter\"><span class=\"label\">twitter</a></li>\r\n");
      out.write("         <li><a href=\"https://www.facebook.com\" target=\"_blank\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("         <li><a href=\"https://www.instagram.com\" target=\"_blank\" class=\"icon fa-instagram\"><span\r\n");
      out.write("               class=\"label\">Instagram</span></a></li>\r\n");
      out.write("         <li><a href=\"https://www.pinterest.co.kr\" target=\"_blank\" class=\"icon fa-pinterest\"><span\r\n");
      out.write("               class=\"label\">Pinterest</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Menu -->\r\n");
      out.write("\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t<li>&copy; Untitled</li>\r\n");
      out.write("\t\t\t<li>Design: <a href=\"https://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.poptrox.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
